### ISSUE TITLE
Using of additional notification keys requires duplication of 'Message' & 'Title' service data

### ISSUE THREAD

**Issue by mutasim** [home-assistant/home-assistant-android#349]
**Home Assistant Android version: 1.6.0**
**Android version: 10**
**Phone model: Pixel 2XL**
**Home Assistant version: 0.105.2** 

**Description of problem:**
When using notification keys such as 'tag' or 'color' (I suspect this was never formally support yet..) the 'Message' & 'Title' keys aren't being passed through and thus need to be replaced in the data > android > notification part of the payload. 

**Previously Working**

```
message: 'Body Text'
title: 'Title Text'
data:
  android:
    notification:
      color: '#e8e8e8'
      tag: 'my_notification'
```

**Current Behaviour**

Notification sends, but title & message are missing. I believe in using these keys within data > android > notification, it is now also looking for 'body' & 'title' keys within to provide the message and title. 

**Current workaround**

```
message: 'WORKAROUND'
title: 'WORAROUND'
data:
  android:
    notification:
      color: '#e8e8e8'
      tag: 'my_notification'
      body: 'Body Text'
      title: 'Title Text'
```

(Note that some dummy text needs to be inputted into the 'message' & 'title' keys as the service won't work without them). Using this workaround will continue to allow support for using of Notification Tags which are a useful feature.

**Comment by TazUk** [comment]
**Confirming this issue.
The app update breaks all my existing notifications that push an image.**

**Home Assistant Android version: 1.6.0
Android version: 10
Phone model: Pixel 3
Home Assistant version: 0.105.2 (also 0.104.3)**

**Description of problem:**
Existing notifications with images no longer display title or message text after the app update, only the image. Text only notifications without additional data keys are unaffected.

**Previously Working**
```
title: 'Title Text'
message: 'Body Text'
data:
  android:
    notification:
      image: 'url'

```
**Current Behaviour**
Notification sends, title and message are absent and only image is displayed. 
Notifications without images are unaffected.

**Current workaround**
```
title: 'Title Text'
message: 'Body Text'
data:
  android:
    notification:
      title: 'Title Text'
      body: 'Body Text'
      image: 'url'
```

**Comment by JBassett** [comment]
Does that workaround work when the application is open or only when it's closed?

**Comment by mutasim** [comment]
Just tested it - works when the app is open and closed.

**Comment by JBassett** [comment]
So after digging into this for a bit I think we need to, for now, restrict when can be sent via push.  We should only allow what we truly support.  Because of the data you are sending you are bypassing our on device handling of the message.  This is going to cause issues and confusion when you go to implement actionable notifications in the future.  These are the options that we support currently:
```
title: 'Title Text'
message: 'Body Text'
data:
  actions:
    - action: test
      title: Click Me
  data:
    image: 'imageUrl'
```
The only required field is message, everything else is optional.

**Comment by mutasim** [comment]
For what it's worth, I was able to setup actionable notifications successfully even with the workaround. Didn't do any robust testing around it, just a POC. 

Make sense to limit to only what's supported though.

**Comment by andriej** [comment]
It would be nice then to allow other parameters to be sent/used, like tag.
Or colours.

**Comment by TazUk** [comment]
@JBassett 
Thanks for clarifying this - it looks like I trod the wrong path when first setting up my notifications. I've fixed my image-based notifications to follow the supported path.

**Comment by mutasim** [comment]
> It would be nice then to allow other parameters to be sent/used, like tag.
> Or colours.

Sticky is another useful one - great for allowing a notification to stay after being clicked (swipe to dismiss)

**Comment by JBassett** [comment]
It's actually my fault, I should have put together better documentation on what the scheme for sending notifications is.  I have a PR on the server side to restrict to known data fields the application can handle: https://github.com/home-assistant/mobile-apps-fcm-push/pull/5
This is what we will handle after the PR is merged:
```
title: 'title'
message: 'message' # REQUIRED
data:
  actions: # Up to 3 actions
    - title: 'Click Me'
      action: 'clicked'
  image: 'url' # Must be publicly facing for now
  ttl: 0
  priority: high
```

Obviously this will reduce some functionality for now.  If you have a need for additional notification functionality then we should add proper support (enhancement request) for it rather than rely on the system to handle it, because it can be inconsistent.
