### ISSUE TITLE
Feature request: notification tag

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-android#354]
**Home Assistant Android version:** 1.6.0

**Android version:** 10

**Phone model:** OnePlus 6

**Home Assistant version:** 0.105.2

**Last working Home Assistant release (if known):** None

**Description of problem:**
Tag is the unique identifier of the notification. Can be overridden when sending a notification to allow for replacing existing notifications. Now I add `tag` like this:
```
title: 'Title'
message: 'Body'
data:
  android:
    notification:
      title: 'Title'
      body: 'Body'
      tag: 'unique-string'
```
But this way will soon be [disabled](https://github.com/home-assistant/mobile-apps-fcm-push/pull/5).
Any chance to add this feature?
