### ISSUE TITLE
Actionable notifications, not working

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/home-assistant-android#360]
**Home Assistant Android version:**
1.6.0

**Android version:**
10

**Phone model:**
pixel2

**Home Assistant version:**
0.105.2

**Last working Home Assistant release (if known):**
na

**Description of problem:**

When testing the service in Home Assistant with

```
message: 'Something really cool happened'
title: 'Action Time'
data:
      data:
        action_1_key: 'EVENT_KEY'
        action_1_title: 'Button Text'
        action_2_key: 'EVENT_KEY2'
        action_2_title: 'Button Text 2'
```

I receive a notification, but without buttons. Is this a bug or is my syntax wrong?

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by dshokouhi** [comment]
The format has changed actually.  I just updated the companion docs, take a look at the android example:

https://companion.home-assistant.io/en/notifications/actionable#building-automations-for-notification-actions

new format is as follows;

```
    action:
      service: notify.mobile_app_<your_device_id_here>
      data:
        message: "Something happened at home!"
        data:
          actions:
            - action: "alarm" # The key you are sending for the event
              title: "Title" 
```

**Comment by SamJongenelen** [comment]
Ill try it immidiately

**Comment by SamJongenelen** [comment]
Unfortunately, this still wont work.

My current HA call service content:
```
message: testmessage
data:
  actions:
    - action: "alarm"
      title: "Title" 
```

**Comment by dshokouhi** [comment]
My wifes phone had a similar issue and I ended up having to clear data and starting fresh on her phone for the actions to show up.  You may need to do that too and try again to see if they show up.

**Comment by jcullen86** [comment]
The message title is missing from the docs

eg:
```
action:
      service: notify.mobile_app_<your_device_id_here>
      data:
        message: "Something happened at home!"
        title: "Check this out!"
        data:
          actions:
            - action: "alarm" # The key you are sending for the event
              title: "Title"
```
