### ISSUE TITLE
Action buttons in notification are not sending data to HA

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/home-assistant-android#375]
**Home Assistant Android version:**
1.6.0 (111)
**Android version:**
10
**Phone model:**
OnePlus 6T
**Home Assistant version:**
105.3
**Last working Home Assistant release (if known):**

**Description of problem:**
action buttons in notifications are not sending data to HA. listening to `mobile_app_notification_action` in HA doesn't show any event data.
**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by dshokouhi** [comment]
Can you share the service data that you used?

**Comment by engrbm87** [comment]
I used this:
```
title: 'Title Text'
message: 'Body Text'
data:
  actions:
    - action: test
      title: Click Me
    - action: URI
      title: Open Url
      uri: https://google.com
```
