### ISSUE TITLE
Allow relative urls for image (and possibly clickAction) in notifications

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/home-assistant-android#390]
When sending notifications with the image property, it is necessary to include the full URL. Allowing this to be relative to the Home Assistant server would allow the image to be opened via the local or remote URL depending on wether we are connected to the local network. Something like this:

```
service: notify.mobile_app_my_phone
data:
  message: Hello
  data:
    image: /local/my_image.png
```

If the same could also be done for clickAction, it may be an alternative way of resolving https://github.com/home-assistant/home-assistant-android/issues/382 as relative URLS could be opened directly in the app.
