### ISSUE TITLE
Feature request: Persistent notifications

### ISSUE THREAD

**Issue by stipe76** [home-assistant/home-assistant-android#403]
I currently have a persistent notification getting updated frequently with important data. I have created this using Tasker, Join and Autonotifications. 

I am using the new tag and sticky options in a Companion notification, which are working fine, but I'd like the notification to be persistent, and not be able to be swiped away. 

Would it be possible to add this feature? It would definitely simplify my setup, requiring 3 less apps in my system. 

Thanks!

**Comment by robbiet480** [comment]
No

**Comment by robbiet480** [comment]
Actually just kidding, it's already implemented :)

**Comment by robbiet480** [comment]
This will make the notification permanent.

```yaml
message: 'Would you like to unlock the door?'
title: 'Welcome Home'
data:
    sticky: true
```
