### ISSUE TITLE
Notification action click does not dismiss notification when tag attribute is present in data attribute

### ISSUE THREAD

**Issue by PTST** [home-assistant/home-assistant-android#445]
**Home Assistant Android version:** 1.7.2-128

**Android version:** 10

**Phone model:** Samsung Galaxy S10+ (SM-G975F)

**Home Assistant version:** 0.105.4

**Last working Home Assistant release (if known):** N/A

**Description of problem:**

Notification action click does not dismiss notification when tag attribute is present i data attribute

Example service call where notification is not dismissed on action click:  
```yaml
title: Message Title
message: Message Info
data:
  tag: 1
  actions:
  - action: action_1
    title: Action_1
  - action: action_2
    title: Action_2
```

Example service call where notification is dismissed on action click (expected behaviour):  
```yaml
title: Message Title
message: Message Info
data:
  actions:
  - action: action_1
    title: Action_1
  - action: action_2
    title: Action_2
```

**Traceback (if applicable):**

```
N/A
```

**Screenshot of problem:**

**Additional information:**
