### ISSUE TITLE
URI in actionable notifications is not working when application open

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#467]
**Home Assistant Android version:**
1.7.2-137 (137)
**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
0.105.5
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**

After updating to build 137 I can see several of the new notification enhancements.  When I attempt to use `uri` in my `actions` nothing happens.  Neither a normal URL, which was previously working (https://www.google.com/) or even a lovelace view `/lovelace/settings` load anything.  The notification is just dismissed.  When I use `clickAction` the lovelace view loads as expected.  The relative camera URL is also working for `image`.

Example:

```
service: notify.mobile_app
message: test
data:
  actions:
  - action: test
    title: test
    uri: /lovelace/settings
```

I have also tried

```
uri: https://www.google.com
```

**Traceback (if applicable):**

```
N/A
```

**Screenshot of problem:**

No screenshot as the notification just dismisses without any action occurring.

**Additional information:**

The action event still get sent when the action is selected so seems to just be a URL loading issue.

**Comment by JBassett** [comment]
In order for the uri handling to happen you need to set the action to `URI`
Example:
```
service: notify.mobile_app
message: test
data:
  actions:
  - action: URI
    title: test
    uri: /lovelace/settings
```
