### ISSUE TITLE
Application doesn't open the right lovelace view from the relative URL in clickAction

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-android#486]
**Home Assistant Android version:** 1.8.0-144

**Android version:** 10

**Phone model:** OnePlus 6

**Home Assistant version:** 0.106.2

**Last working Home Assistant release (if known):** None

**Description of problem:**
The application doesn't open the right lovelace view from the relative URL in `clickAction`. First lovelace view is always opened. This problem doesn't occur if I use action button with URL in `notify` service.

Notify service configuration:
```yaml
message: TEST
data:
  clickAction: /lovelace/energy
```
My lovelace config has energy view:
```yaml
- id: energy
    icon: mdi:power-plug
    title: "Energia"
    path: energy
    panel: true
    cards:
      - ...
      - ...
```
`http` configuration:
```
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: "127.0.0.1"
  base_url: "https://my_domain.org"
```

**Video of problem:**

[![Watch the video](https://i.ytimg.com/vi/UI60fBQTnHQ/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDUSi2MfaJmnpIJkwAh8laMM_bQMQ)](https://youtu.be/UI60fBQTnHQ)
