### ISSUE TITLE
Notification does not dismiss on clicking action

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/home-assistant-android#504]
**Home Assistant Android version:**
1.8.0-150
**Android version:**
9 (up to date)
**Phone model:**
Samsung A50
**Home Assistant version:**
0.106.2
**Last working Home Assistant release (if known):**
0.105.x (I think)
**Description of problem:**
Whenever I used to click an action in a notification, the notification got dismissed. However, the notification now stays in the notification bar until I dismiss it manually.

**Traceback (if applicable):**
n/a

**Screenshot of problem:**
n/a (notification icon, message and actions just stay in notification area until dismissed)

**Additional information:**
relevant config:
```
..........automation trigger&conditions.....
  action:
  - service: notify.mobile_app_sm_a505fn
    data:
      message: 'Het wordt bijna donker. Wil je de lampen aan?'
      title: 'Magic lights'
      data:
        actions:
          - action: 'turn_on_sunset_lights'
            title: 'Ja, graag!'
          - action: 'nee'
            title: 'Nee, dank je!'
        ttl: 0
        priority: high
```

Might be related to #445 but I'm not using tag
